name: CI
on: [push]
jobs:
  build:
    name: setup
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install --upgrade pip  poetry
          poetry install
      - name: Test and cov
        run: |
          poetry run pytest --cov=pypackage_boilerplate tests
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: htmlcov
      - name: Lint
        run: |
          poetry run flake8 tests conf.py
          poetry run isort --check --diff tests conf.py pypackage_boilerplate
          poetry run black --check tests conf.py pypackage_boilerplate
          poetry run mypy tests conf.py pypackage_boilerplate